import { PrismaClient } from "@prisma/client";

export const corePermissions = [
  "dashboard.view",
  "pos.access",
  "pos.catalog.view",
  "pos.sell",
  "pos.hold_order",
  "pos.view_recent_invoices",
  "products.view",
  "products.create",
  "products.update",
  "products.delete",
  "categories.view",
  "categories.create",
  "categories.update",
  "categories.delete",
  "inventory.view",
  "inventory.adjust",
  "inventory.add_stock",
  "inventory.remove_stock",
  "inventory.view_movements",
  "inventory.view_alerts",
  "inventory.transfer",
  "sales.view",
  "invoices.view",
  "invoices.print",
  "invoices.refund",
  "shifts.open",
  "shifts.close",
  "shifts.view",
  "returns.view",
  "returns.create",
  "returns.cancel",
  "returns.approve",
  "expenses.view",
  "expenses.create",
  "expenses.update",
  "expenses.delete",
  "reports.view",
  "reports.export",
  "data.import",
  "data.export",
  "products.import",
  "products.export",
  "inventory.import",
  "inventory.export",
  "closing.view",
  "closing.create",
  "customers.view",
  "customers.create",
  "customers.update",
  "customers.delete",
  "debts.view",
  "debts.add",
  "debts.pay",
  "debts.adjust",
  "suppliers.view",
  "suppliers.create",
  "suppliers.update",
  "suppliers.delete",
  "suppliers.pay",
  "suppliers.adjust",
  "purchase_orders.view",
  "purchase_orders.create",
  "purchase_orders.update",
  "purchase_orders.cancel",
  "purchase_orders.receive",
  "subscription.view",
  "subscription.request_upgrade",
  "settings.receipt.view",
  "settings.receipt.update",
  "backup.manage",
  "license.manage",
  "printing.receipts",
  "printing.barcodes",
  "products.generate_barcode",
  "users.manage",
  "settings.manage",
  "activity_logs.view",
  "admin.platform_access",
  "admin.stores.view",
  "admin.stores.create",
  "admin.stores.update",
  "admin.stores.suspend",
  "admin.stores.activate",
  "admin.plans.view",
  "admin.plans.create",
  "admin.plans.update",
  "admin.subscriptions.view",
  "admin.subscriptions.update",
  "admin.payments.view",
  "admin.payments.create",
  "admin.usage.view",
];

export const rolePermissions: Record<string, string[]> = {
  super_admin: [...corePermissions],
  owner: corePermissions.filter((permission) => !permission.startsWith("admin.")).concat(["subscription.view", "subscription.request_upgrade"]),
  manager: [
    "dashboard.view",
    "pos.access",
    "pos.sell",
    "pos.hold_order",
    "pos.view_recent_invoices",
    "products.view",
    "products.create",
    "products.update",
    "categories.view",
    "categories.create",
    "categories.update",
    "inventory.view",
    "inventory.adjust",
    "inventory.add_stock",
    "inventory.remove_stock",
    "inventory.view_movements",
    "inventory.view_alerts",
    "inventory.transfer",
    "sales.view",
    "invoices.view",
    "invoices.print",
    "invoices.refund",
    "shifts.open",
    "shifts.close",
    "shifts.view",
    "returns.view",
    "returns.create",
    "returns.cancel",
    "returns.approve",
    "expenses.view",
    "expenses.create",
    "expenses.update",
    "expenses.delete",
    "reports.view",
    "reports.export",
    "data.import",
    "data.export",
    "products.import",
    "products.export",
    "inventory.import",
    "inventory.export",
    "closing.view",
    "closing.create",
    "customers.view",
    "customers.create",
    "customers.update",
    "customers.delete",
    "debts.view",
    "debts.add",
    "debts.pay",
    "debts.adjust",
    "suppliers.view",
    "suppliers.create",
    "suppliers.update",
    "suppliers.delete",
    "suppliers.pay",
    "suppliers.adjust",
    "purchase_orders.view",
    "purchase_orders.create",
    "purchase_orders.update",
    "purchase_orders.cancel",
    "purchase_orders.receive",
    "settings.receipt.view",
    "settings.receipt.update",
    "printing.receipts",
    "printing.barcodes",
    "products.generate_barcode",
    "users.manage",
    "activity_logs.view",
    "subscription.view",
  ],
  cashier: [
    "dashboard.view",
    "pos.access",
    "pos.catalog.view",
    "pos.sell",
    "pos.hold_order",
    "pos.view_recent_invoices",
    "categories.view",
    "inventory.view",
    "inventory.view_alerts",
    "sales.view",
    "invoices.view",
    "invoices.print",
    "printing.receipts",
    "printing.barcodes",
    "shifts.open",
    "shifts.close",
    "shifts.view",
    "returns.view",
    "returns.create",
    "reports.view",
    "closing.view",
    "closing.create",
    "settings.receipt.view",
    "settings.receipt.update",
    "backup.manage",
    "license.manage",
  ],
  inventory: [
    "products.view",
    "products.import",
    "products.export",
    "products.generate_barcode",
    "categories.view",
    "suppliers.view",
    "purchase_orders.view",
    "purchase_orders.receive",
    "inventory.view",
    "inventory.import",
    "inventory.export",
    "inventory.adjust",
    "inventory.add_stock",
    "inventory.remove_stock",
    "inventory.view_movements",
    "inventory.view_alerts",
    "inventory.transfer",
    "printing.barcodes",
  ],
};

export async function seedCoreReferenceData(prisma: PrismaClient) {
  for (const key of corePermissions) {
    await prisma.permission.upsert({
      where: { key },
      update: {},
      create: {
        key,
        label: key,
        description: `Permission: ${key}`,
      },
    });
  }

  await prisma.subscriptionPlan.upsert({
    where: { code: "basic" },
    update: {
      name: "Basic",
      description: "خطة مناسبة للمتاجر الصغيرة بفرع واحد.",
      priceMonthly: 500,
      priceYearly: 5400,
      maxUsers: 2,
      maxBranches: 1,
      maxProducts: 500,
      maxInvoicesPerMonth: 1000,
      features: { support: "business_hours", reports: true, inventory: true },
      status: "ACTIVE",
    },
    create: {
      code: "basic",
      name: "Basic",
      description: "خطة مناسبة للمتاجر الصغيرة بفرع واحد.",
      priceMonthly: 500,
      priceYearly: 5400,
      maxUsers: 2,
      maxBranches: 1,
      maxProducts: 500,
      maxInvoicesPerMonth: 1000,
      features: { support: "business_hours", reports: true, inventory: true },
      status: "ACTIVE",
    },
  });

  await prisma.subscriptionPlan.upsert({
    where: { code: "pro" },
    update: {
      name: "Pro",
      description: "الخطة المناسبة لمعظم المتاجر النشطة متعددة المستخدمين.",
      priceMonthly: 900,
      priceYearly: 9720,
      maxUsers: 5,
      maxBranches: 2,
      maxProducts: 3000,
      maxInvoicesPerMonth: 5000,
      features: { support: "priority", reports: true, inventory: true, purchaseOrders: true },
      status: "ACTIVE",
    },
    create: {
      code: "pro",
      name: "Pro",
      description: "الخطة المناسبة لمعظم المتاجر النشطة متعددة المستخدمين.",
      priceMonthly: 900,
      priceYearly: 9720,
      maxUsers: 5,
      maxBranches: 2,
      maxProducts: 3000,
      maxInvoicesPerMonth: 5000,
      features: { support: "priority", reports: true, inventory: true, purchaseOrders: true },
      status: "ACTIVE",
    },
  });

  await prisma.subscriptionPlan.upsert({
    where: { code: "business" },
    update: {
      name: "Business",
      description: "خطة موسعة للمتاجر متعددة الفروع والفرق الأكبر.",
      priceMonthly: 1500,
      priceYearly: 16200,
      maxUsers: 15,
      maxBranches: 5,
      maxProducts: 10000,
      maxInvoicesPerMonth: 20000,
      features: { support: "priority", reports: true, inventory: true, purchaseOrders: true, advancedUsers: true },
      status: "ACTIVE",
    },
    create: {
      code: "business",
      name: "Business",
      description: "خطة موسعة للمتاجر متعددة الفروع والفرق الأكبر.",
      priceMonthly: 1500,
      priceYearly: 16200,
      maxUsers: 15,
      maxBranches: 5,
      maxProducts: 10000,
      maxInvoicesPerMonth: 20000,
      features: { support: "priority", reports: true, inventory: true, purchaseOrders: true, advancedUsers: true },
      status: "ACTIVE",
    },
  });

  await prisma.subscriptionPlan.upsert({
    where: { code: "enterprise" },
    update: {
      name: "Enterprise",
      description: "خطة مخصصة للسلاسل الكبيرة مع حدود مرتفعة ودعم مخصص.",
      priceMonthly: 0,
      priceYearly: 0,
      maxUsers: 100,
      maxBranches: 50,
      maxProducts: 100000,
      maxInvoicesPerMonth: null,
      features: { support: "dedicated", reports: true, inventory: true, purchaseOrders: true, customPricing: true },
      status: "ACTIVE",
    },
    create: {
      code: "enterprise",
      name: "Enterprise",
      description: "خطة مخصصة للسلاسل الكبيرة مع حدود مرتفعة ودعم مخصص.",
      priceMonthly: 0,
      priceYearly: 0,
      maxUsers: 100,
      maxBranches: 50,
      maxProducts: 100000,
      maxInvoicesPerMonth: null,
      features: { support: "dedicated", reports: true, inventory: true, purchaseOrders: true, customPricing: true },
      status: "ACTIVE",
    },
  });
}
